version: '2'

services:
  mysql-master:
    image: 'mysql:5.7'
    hostname: 'master'
    container_name: 'mysql-master'
    ports:
      - 3307:3306
    volumes:
      - $PWD/master/conf.d:/etc/mysql/mysql.conf.d
      - $PWD/master/data:/var/lib/mysql
      - $PWD/master/log:/var/log/mysql
      - $PWD/master/backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=dbase
  mysql-slave:
    image: 'mysql:5.7'
    hostname: 'slave'
    container_name: 'mysql-slave'
    ports:
      - 3308:3306
    volumes:
      - $PWD/slave/conf.d:/etc/mysql/mysql.conf.d
      - $PWD/slave/data:/var/lib/mysql
      - $PWD/slave/log:/var/log/mysql
      - $PWD/slave/backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=dbase
    depends_on:
      - mysql-master
  mysql-slave-second:
    image: 'mysql:5.7'
    hostname: 'slave-second'
    container_name: 'mysql-slave-second'
    ports:
      - 3309:3306
    volumes:
      - $PWD/slave-second/conf.d:/etc/mysql/mysql.conf.d
      - $PWD/slave-second/data:/var/lib/mysql
      - $PWD/slave-second/log:/var/log/mysql
      - $PWD/slave-second/backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=dbase
    depends_on:
      - mysql-master
